server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-shiro?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: 1234

  redis:
    datasource: 0
    host: localhost
    port: 6379
    timeout: 60000
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1
        min-idle: 0



mybatis:
    mapper-locations: classpath:/mapper/*.xml
